### ISSUE TITLE
Mejoras en la UI/UX

### ISSUE THREAD

**Issue by moisesloyolabarrenechea** [moisesloyolabarrenechea/AgenciaDeViajes#1]
Creo que deberíamos optar por una interfaz más sencilla, ya que la actual es complicada y poco intuitiva. Aquí dejo algunos estilos que podríamos implementar en nuestra versión.

www.example.com

**Comment by rodrig2024** [comment]
Me gustaría que implementáramos ese estilo en nuestra página, ya que sería mucho más sencillo para los usuarios.
